version: "3.9"
services:
  realtytrends-db:
    container_name: realtytrends-db
    image: "postgres:15.3-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external : internal
      - "5445:5432"
    volumes:
      - realtytrends-postgres-volume:/var/lib/postgresql/data
volumes:
  realtytrends-postgres-volume: